-- ==============================================================================
-- OASIS SUPABASE MIGRATION SCRIPT
-- ==============================================================================
-- Ejecuta este script en el SQL Editor de tu proyecto en Supabase
-- ==============================================================================

-- 1. EXTENSIÓN NECESARIA PARA CRIPTOGRAFÍA
create extension if not exists "pgcrypto";

-- ==============================================================================
-- 2. CREACIÓN DE TABLAS DEL PROYECTO
-- ==============================================================================

-- Tabla de Anuncios / Novedades
create table public.announcements (
  id bigint generated by default as identity primary key,
  title text not null,
  content text,
  tag text,
  image_url text,
  date date,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Tabla de Cartelera Principal (Hero)
create table public.billboards (
  id bigint generated by default as identity primary key,
  title text not null,
  subtitle text,
  media_url text,
  media_type text default 'image'::text,
  "order" integer default 0,
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Tabla de Configuraciones Generales
create table public.settings (
  id bigint generated by default as identity primary key,
  contact_email text,
  contact_phone text,
  hero_live_active boolean default false,
  hero_live_url text,
  hero_live_bg text,
  wa_instance_name text,
  wa_api_key text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
-- Insertar configuración inicial por defecto
insert into public.settings (contact_email, hero_live_active) values ('admin@oasis.com', false);

-- Tabla de Peticiones y Solicitudes
create table public.requests (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text,
  email text,
  category text,
  content text,
  status text default 'pending'::text,
  wa_link_opened_at timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Tabla de Recursos Descargables
create table public.resources (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  file_url text,
  category text,
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Tabla de Formularios Dinámicos
create table public.event_forms (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  is_active boolean default true,
  fields jsonb default '[]'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Tabla de Envío de Formularios
create table public.event_submissions (
  id bigint generated by default as identity primary key,
  event_form_id bigint references public.event_forms(id) on delete cascade,
  data jsonb not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Tabla de Perfiles de Usuario (viculada a auth.users de Supabase)
create table public.profiles (
  id uuid references auth.users(id) on delete cascade primary key,
  name text,
  email text,
  role text default 'admin'::text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- ==============================================================================
-- 3. CONFIGURACIÓN DE STORAGE (ALMACENAMIENTO DE ARCHIVOS)
-- ==============================================================================

-- Crear un bucket público llamado 'media'
insert into storage.buckets (id, name, public) 
values ('media', 'media', true) 
on conflict (id) do nothing;

-- Crear un bucket público llamado 'resources'
insert into storage.buckets (id, name, public) 
values ('resources', 'resources', true) 
on conflict (id) do nothing;

-- Políticas de Storage (Permitir lectura pública y escritura general para simplificar por ahora)
create policy "Media Public Access" on storage.objects for select using ( bucket_id = 'media' );
create policy "Media Insert Access" on storage.objects for insert with check ( bucket_id = 'media' );
create policy "Media Update Access" on storage.objects for update using ( bucket_id = 'media' );
create policy "Media Delete Access" on storage.objects for delete using ( bucket_id = 'media' );

create policy "Resources Public Access" on storage.objects for select using ( bucket_id = 'resources' );
create policy "Resources Insert Access" on storage.objects for insert with check ( bucket_id = 'resources' );
create policy "Resources Update Access" on storage.objects for update using ( bucket_id = 'resources' );
create policy "Resources Delete Access" on storage.objects for delete using ( bucket_id = 'resources' );

-- ==============================================================================
-- 4. CREACIÓN DEL USUARIO ADMINISTRADOR INICIAL EN SUPABASE AUTH
-- ==============================================================================
-- IMPORTANTE: Cambia el correo electronico y la contraseña en la siguiente linea:

DO $$
DECLARE
  new_user_id uuid := gen_random_uuid();
  admin_email text := 'admin@oasis.com';      -- <-- CAMBIA ESTO POR TU CORREO
  admin_password text := 'admin123';           -- <-- CAMBIA ESTO POR TU CONTRASEÑA
BEGIN
  -- 1. Insertar el usuario en el sistema de Auth de Supabase
  INSERT INTO auth.users (
    id, email,
    encrypted_password,
    email_confirmed_at,
    created_at, updated_at,
    raw_app_meta_data, raw_user_meta_data, is_super_admin, role
  )
  VALUES (
    new_user_id, admin_email,
    crypt(admin_password, gen_salt('bf')),
    now(),
    now(), now(),
    '{"provider":"email","providers":["email"]}', '{"role":"admin"}', FALSE, 'authenticated'
  )
  ON CONFLICT (email) DO NOTHING;

  -- 2. Vincular el usuario a la tabla publica de perfiles
  INSERT INTO public.profiles (id, name, email, role)
  SELECT id, 'Administrador OASIS', email, 'admin' 
  FROM auth.users WHERE email = admin_email
  ON CONFLICT (id) DO NOTHING;
END $$;
